# Production Configuration for Financial Data Collector
app:
  name: "Financial Data Collector"
  version: "1.0.0"
  debug: false
  log_level: "INFO"

# Database configuration
database:
  url: "${DATABASE_URL}"
  pool_size: 20
  max_overflow: 30
  echo: false
  pool_pre_ping: true
  pool_recycle: 3600

# Redis configuration
redis:
  url: "${REDIS_URL}"
  max_connections: 50
  socket_timeout: 10
  socket_connect_timeout: 10
  retry_on_timeout: true

# API configuration
api:
  host: "0.0.0.0"
  port: 8000
  debug: false
  cors:
    enabled: true
    origins: ["https://yourdomain.com"]
  rate_limiting:
    enabled: true
    requests_per_minute: 100

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers:
    console:
      enabled: true
      level: "INFO"
    file:
      enabled: true
      level: "WARNING"
      filename: "/app/logs/fdc.log"
      max_bytes: 52428800  # 50MB
      backup_count: 10

# Security
security:
  api_key_required: true
  api_key: "${API_KEY}"
  encryption:
    enabled: true
    algorithm: "AES-256-GCM"
    key: "${ENCRYPTION_KEY}"
  rate_limiting:
    enabled: true
    requests_per_minute: 100
  cors:
    enabled: true
    allowed_origins: ["https://yourdomain.com"]

# Performance
performance:
  max_memory_usage: "2GB"
  gc_threshold: 0.8
  async_workers: 20
  connection_pool_size: 50

# Health monitoring
health_monitoring:
  enabled: true
  interval: 30
  timeout: 10
  alert_threshold: 3
  recovery_threshold: 2

# External services
external_services:
  alpha_vantage:
    api_key: "${ALPHA_VANTAGE_API_KEY}"
    base_url: "https://www.alphavantage.co/query"
    rate_limit: 5  # requests per minute
  
  yahoo_finance:
    base_url: "https://query1.finance.yahoo.com"
    rate_limit: 10
  
  quandl:
    api_key: "${QUANDL_API_KEY}"
    base_url: "https://www.quandl.com/api/v3"
    rate_limit: 10
