apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "5s"
      queryTimeout: "60s"
      httpMethod: "POST"
    secureJsonData: {}
    version: 1
    orgId: 1
    uid: prometheus

  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: fdc_db
    user: fdc_user
    secureJsonData:
      password: fdc_password
    jsonData:
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
    version: 1
    orgId: 1
    uid: postgres

  - name: Redis
    type: redis-datasource
    access: proxy
    url: redis:6379
    jsonData:
      client: standalone
      poolSize: 5
    secureJsonData:
      password: redis_password
    version: 1
    orgId: 1
    uid: redis
